language: node_js

node_js:
  - node

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  # https://github.com/babel/eslint-plugin-babel
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

script:
  - make lint
  - make test -- --coverage

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/no-unresolved: 0
  import/extensions: 0
