name: checkLinter
on: [push]

jobs:
  build:
    name: checklinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: makelint
        run: |
          make Install
          make lint
