name: checkLinter
on: 
  - push

jobs:
  build:
    
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [13.x]
  
    
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: |
          make install

      - name: Run linter
        run: |
          make lint
          
